name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-13-xlarge

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash Script
        run: bash build.sh

      - name: Store Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
